### ISSUE TITLE
Fauxton failing to build on Centos 7 CI container

### ISSUE THREAD

**Issue by willholley** [apache/couchdb-fauxton#1230]
#Expected Behavior
`npm run webpack:release` should run successfully on all supported platforms.

## Current Behavior
Fauxton is failing to build on the Centos 7 CI container (`couchdbdev/centos-7-erlang-19.3.6:latest`). Currently the container uses:

 * npm 6.4.1
 * node v8.16.0

Error is:

```
ERROR in ./app/main.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'acorn'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/src/couchdb/src/fauxton/node_modules/acorn-jsx/index.js:8:15)
    at Module._compile (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/src/couchdb/src/fauxton/node_modules/espree/espree.js:62:13)
    at Module._compile (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/src/couchdb/src/fauxton/node_modules/eslint/lib/linter/linter.js:17:14)
    at Module._compile (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/src/couchdb/src/fauxton/node_modules/eslint/lib/linter/index.js:3:20)
    at Module._compile (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/src/couchdb/src/fauxton/node_modules/eslint/lib/cli-engine/cli-engine.js:24:20)
    at Module._compile (/usr/src/couchdb/src/fauxton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
 @ multi core-js/fn/array core-js/fn/string/ends-with core-js/fn/string/starts-with core-js/fn/object core-js/fn/symbol core-js/fn/promise regenerator-runtime/runtime ./app/main.js bundle[7]
```

Fauxton 1.2.0 updated webpack from `"~3.12.0` to `^4.35.3` so I wonder whether https://github.com/webpack/webpack/issues/8656 is related. I cannot reproduce the problem locally on MacOS with the same node/npm versions but can produce the error in the Docker container.

## Possible Solution
 * Add webpack:release to the fauxton build / Travis so we verify the step there
 * Add an explicit dependency on acorn?

## Steps to Reproduce (for bugs)
A simple Dockerfile to reproduce the error:

```
FROM couchdbdev/centos-7-erlang-19.3.6:latest
USER root
WORKDIR /usr/src

RUN set -xe; \
    git clone https://github.com/apache/couchdb-fauxton; \
    cd couchdb-fauxton; \
    npm install --production && ./node_modules/grunt-cli/bin/grunt couchdb
```

**Comment by popojargo** [comment]
Have you tried updating webpack version?
