### ISSUE TITLE
Build fails with Cannot find module 'foreach'

### ISSUE THREAD

**Issue by janl** [apache/couchdb-fauxton#1321]
I’m trying to build Fauxton from source, but with any of the [documented commands](https://github.com/apache/couchdb-fauxton#running-fauxton), I get a build error that looks like this:

```
> npm run dev

> fauxton@1.2.6 dev
> node ./devserver.js

internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module 'foreach'
Require stack:
- /Users/jan/Work/asf/couchdb-fauxton/node_modules/define-properties/index.js
- /Users/jan/Work/asf/couchdb-fauxton/node_modules/html-webpack-plugin/node_modules/util.promisify/index.js
- /Users/jan/Work/asf/couchdb-fauxton/node_modules/html-webpack-plugin/index.js
- /Users/jan/Work/asf/couchdb-fauxton/webpack.config.dev.js
- /Users/jan/Work/asf/couchdb-fauxton/devserver.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/jan/Work/asf/couchdb-fauxton/node_modules/define-properties/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jan/Work/asf/couchdb-fauxton/node_modules/define-properties/index.js',
    '/Users/jan/Work/asf/couchdb-fauxton/node_modules/html-webpack-plugin/node_modules/util.promisify/index.js',
    '/Users/jan/Work/asf/couchdb-fauxton/node_modules/html-webpack-plugin/index.js',
    '/Users/jan/Work/asf/couchdb-fauxton/webpack.config.dev.js',
    '/Users/jan/Work/asf/couchdb-fauxton/devserver.js'
  ]
}
```

```
> node --version
v12.8.0
> npm --version
7.14.0
```

**Comment by janl** [comment]
PEBCAK
